# Site settings
title: Developmentr
email: rob.scott@developmentr.com
description: > # this means to ignore newlines until "baseurl:"
  Developmentr provides excellent development tutorials and information
  and helps you grow as a developer.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://developmentr.com" # the base hostname & protocol for your site
twitter_username: developmentr1
#github_username:  varedis

# Build settings
markdown: kramdown
